spring:
  profiles.active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  sql:
    init:
      data-locations: classpath:data.sql

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:h2:file:./data/local
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    show-sql: true
  h2:
    console:
      enabled: true
